export enum Role {
  CITIZEN = 'CITIZEN',
  MODERATOR = 'MODERATOR',
  ENTITY = 'ENTITY',
  ADMIN = 'ADMIN',
}
export enum ReportStatus {
  CREATED = 'CREATED',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  VALIDATED = 'VALIDATED',
  REJECTED = 'REJECTED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}
